### ISSUE TITLE
Failed to load module script error

### ISSUE THREAD

**Issue by YukhymchukVolodymyr** [Teranode/nuxt-module-alternatives#68]
Hi.

I try to use nuxt3 with this package, because I need nuxt auth.

package.json

```
{
  "private": true,
  "scripts": {
    "build": "nuxi build",
    "dev": "nuxi dev",
    "generate": "nuxi generate",
    "preview": "nuxi preview"
  },
  "devDependencies": {
    "@nuxtjs-alt/auth": "^1.2.12",
    "@nuxtjs-alt/axios": "^1.0.16",
    "@pinia/nuxt": "0.3.1",
    "@vue-leaflet/vue-leaflet": "^0.6.1",
    "nuxt": "3.0.0-rc.8"
  },
  "dependencies": {
    "echarts": "^5.3.3",
    "vue-echarts": "^6.2.3"
  }
}
```
nuxt.config.ts

```
import { defineNuxtConfig } from "nuxt";

export default defineNuxtConfig({
  ssr: false,

  plugins: ["@/plugins/echart"],

  modules: ["@nuxtjs-alt/auth", "@nuxtjs-alt/axios", "@pinia/nuxt"],

  axios: {
    baseURL: process.env.API_URL,
  },

  build: {
    transpile: [/echarts/, "pinia"],
  },
});
```
But I have error in console ![image](https://user-images.githubusercontent.com/65486559/186200305-3633884d-f64f-4b56-a121-30f901938839.png)

If I remove "@nuxtjs-alt/auth" and "@pinia/nuxt" from nuxt.config.ts modules - it works.

Any ideas?

**Comment by Teranode** [comment]
update your pinia version, latest is 0.4.1

**Comment by YukhymchukVolodymyr** [comment]
Great! Thank you!

Somehow I missed that I had 0.3.1 version, I installed package from npm.

After updating to 0.4.1 I got a new error

**ERROR  Cannot start nuxt:  Cannot find module 'pinia/dist/pinia.mjs'                                                                                                                                                10:34:41
Require stack:
- /home/nuxt3/index.js**

So I removed node_modules, package-lock.json and reinstalled all modules and that helped.
